version: '3'
services:

  #PHP Service
  app:
    image: test-docker
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/ssl:/etc/ssl
      - ./.docker/nginx/log:/var/log/nginx/

  #Db Service
  db:
    container_name: test-mysql
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=tuanbh
      - MYSQL_PASSWORD=123456
    ports:
      - "3309:3306"
    volumes:
      - ./.docker/mysql:/var/lib/minesql
      - ./.docker/mysql/dmp:/var/lib/minesql/dmp
      - ./.docker/mysql/db_data:/var/lib/minesql/data
